name: GitHub Actions Environment
on:
  push:
    branches: [ main ]
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment varaibles
        run: env
