name: GitHub Actions Environment
on:
  push:
    branches: [ master ]
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-20.04-arm64
    steps:
      - name: Print environment varaibles
        run: env
